WORKINGDIR=/home/u10153/nagasaka/kyotosrl/docking
PROTEINDIR=${WORKINGDIR}/proteins
LIGANDDIR=${WORKINGDIR}/ligands
BINARY=${WORKINGDIR}/qvina/qvina-w
OUTPUTDIR=${WORKINGDIR}/output
LOGDIR=${WORKINGDIR}/log
